- src/main/java/com/shaftEngine/supportActionLibrary/JavaActions.java
Adding replaceRegex method to JavaActions
> Add New supportAction package, JavaActions class

- src/main/java/com/shaftEngine/supportActionLibrary/JavaActions.java
Implementing replaceRegex with one String parameter
> Add overloaded method to replaceRegex()

- src/main/java/com/shaft/api/RestActions.java
- src/main/java/com/shaft/io/JsonFileManager.java
- Fix patch request issue
- Apply review comments
> Fixing issue with applying review comments

- pom.xml
- src/main/java/com/shaft/io/JsonFileManager.java
- src/main/java/com/shaft/io/ReportManager.java
- src/main/java/com/shaft/io/ScreenshotManager.java
- src/main/java/com/shaft/io/ScreenshotUtils.java
- src/test/java/testPackage01/Test_google.java
. JsonFileManager: fixed linting issue with possible nullable return
. pom.xml: version upgrade, adding screenshotParams_highlightElements,
adding screenshotParams_screenshotType, removing
ru.yandex.qatools.ashot.version, removing
screenshotParams_isFullPageScreenshot
. ReportManager: fixed linting issue with unneeded import from the same
package
. ScreenshotManager: fixed linting issues, added support for new pom.xml
screenshot_params
. ScreenshotUtils: added support for new pom.xml screenshot_params
> Added support for regular/fullPage/element screenshots, and minor fixes

- src/main/java/com/shaft/tools/io/ReportManager.java
- src/main/java/com/shaft/tools/listeners/SuiteListener.java
- src/main/resources/defaultProperties/execution.properties
> Open Allure Report After Local Execution

- src/main/java/com/shaft/gui/element/ElementActions.java
- src/main/java/com/shaft/tools/io/ReportManager.java
- src/test/java/testPackage01/Test_IsElementClickable.java
> Fixes isElementClickable #131 

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- pom.xml
- src/main/java/com/shaft/cli/FileActions.java
- src/main/java/com/shaft/tools/io/ProjectStructureFactory.java
- src/main/java/com/shaft/tools/listeners/SuiteListener.java
- src/main/java/com/shaft/validation/Assertions.java
- src/main/java/com/shaft/validation/Verifications.java
. fixed documentation issues with Assertions and Verifications
. added the ability to copy the default properties from inside the engine jar
. added src/test/resources folder initialization
. created ProjectStructureFactory class which will initialize the project structure on startup
. updated engine version
> bug fixes and user experience enhancement

- src/main/java/com/shaft/gui/element/ElementActions.java
> pushing initial fix for #223

- src/main/java/com/shaft/tools/io/JSONFileManager.java
Fix Bug #249 
Now when we use JSONFileManager we don't need to create an object from the class each time we use it
After Fix :- 
Thanks
> Bug fix#249

- src/main/java/com/shaft/gui/element/ElementActions.java
- src/main/java/com/shaft/gui/element/ElementActionsHelper.java
- src/main/java/com/shaft/gui/element/ElementActionsHelpers.java
> Extracted all wait-related methods from ElementActions

- pom.xml
- src/main/java/com/shaft/gui/browser/BrowserFactory.java
- src/main/java/com/shaft/gui/element/ElementActionsHelper.java
- src/main/javadoc/index.html
> native mobile performance improvements

- pom.xml
- src/main/java/com/shaft/api/BrowserStack.java
- src/main/java/com/shaft/api/RequestBuilder.java
- src/main/java/com/shaft/api/RestActions.java
- src/main/java/com/shaft/cli/FileActions.java
- src/main/java/com/shaft/gui/browser/BrowserFactory.java
- src/main/java/com/shaft/gui/element/ElementActions.java
- src/main/java/com/shaft/gui/element/ElementActionsHelper.java
- src/main/java/com/shaft/gui/element/TouchActions.java
- src/main/java/com/shaft/gui/video/RecordManager.java
- src/main/java/com/shaft/tools/listeners/InvokedMethodListener.java
- src/main/resources/defaultProperties/internal.properties
- src/test/java/testPackage01/Test_AppiumNative.java
> minor enhancements

- .gitignore
- .settings/.gitignore
- pom.xml
- src/main/java/com/shaft/api/BrowserStack.java
- src/main/java/com/shaft/api/RequestBuilder.java
- src/main/java/com/shaft/api/RestActions.java
- src/main/java/com/shaft/cli/FileActions.java
- src/main/java/com/shaft/db/DatabaseActions.java
- src/main/java/com/shaft/gui/element/ElementActions.java
- src/main/java/com/shaft/gui/element/SikuliActions.java
- src/main/java/com/shaft/gui/image/AnimatedGifManager.java
- src/main/java/com/shaft/gui/image/ImageProcessingActions.java
- src/main/java/com/shaft/gui/image/ScreenshotManager.java
- src/main/java/com/shaft/tools/io/ExcelFileManager.java
- src/main/java/com/shaft/tools/io/ReportManagerHelper.java
- src/main/java/com/shaft/tools/support/JavaActions.java
- src/main/java/com/shaft/tools/support/JavaScriptHelper.java
- src/main/java/com/shaft/validation/Assertions.java
- src/main/java/com/shaft/validation/ValidationHelper.java
- src/main/java/com/shaft/validation/Verifications.java
.pom.xml fixed pom conflicts
.removed all unsupported warnings from eclipse
.force scaled down animated gif to 720p to minimize file size
> fixed build issue and pom conflicts for eclipse

- .github/workflows/test.yml
- README.md
- pom.xml
- src/main/java/com/shaft/api/RestActions.java
- src/main/java/com/shaft/cli/TerminalActions.java
- src/main/java/com/shaft/db/DatabaseActions.java
- src/main/java/com/shaft/driver/DriverFactory.java
- src/main/java/com/shaft/driver/DriverFactoryHelper.java
- src/main/java/com/shaft/driver/ShaftDriver.java
- src/main/java/com/shaft/gui/browser/BrowserActions.java
- src/main/java/com/shaft/gui/browser/BrowserFactory.java
- src/main/java/com/shaft/gui/element/ElementActions.java
- src/main/java/com/shaft/gui/element/ElementActionsHelper.java
- src/main/java/com/shaft/gui/element/JavaScriptWaitManager.java
- src/main/java/com/shaft/gui/element/SikuliActions.java
- src/main/java/com/shaft/gui/element/TouchActions.java
- src/main/java/com/shaft/gui/image/ImageProcessingActions.java
- src/main/java/com/shaft/gui/video/RecordManager.java
- src/main/java/com/shaft/tools/io/LogsHelper.java
- src/main/java/com/shaft/tools/listeners/InvokedMethodListener.java
- src/test/java/selfRelease/BuildAndRelease.java
- src/test/java/testPackage01/Test_SelectedValue.java
- src/test/java/testPackage01/Test_chainableElementActions.java
- src/test/java/testPackage01/Test_hover.java
- src/test/java/testPackage01/Test_sikulix.java
> setting up DriverFactory and FactoryHelper

- src/main/java/com/shaft/validation/Assertions.java
- src/main/java/com/shaft/validation/Verifications.java
- src/test/java/testPackage01/Test_AssertApiResponseEquals.java
adding assertApiResponseEquals and verifyApiResponseEquals.
Two methods to assert/verify any API response.
closes #312
> adding API Response assertion methods

- pom.xml
- src/main/java/com/shaft/gui/element/WebDriverElementActions.java
> second fix for typing related null issue

- pom.xml
- src/main/java/com/shaft/cucumber/ElementSteps.java
- src/main/java/com/shaft/gui/element/ElementActions.java
- src/main/java/com/shaft/gui/element/PlayWrightElementActions.java
- src/main/java/com/shaft/gui/element/SikuliActions.java
- src/main/java/com/shaft/gui/element/WebDriverElementActions.java
- src/main/java/com/shaft/gui/image/ScreenshotManager.java
- src/main/java/com/shaft/validation/Assertions.java
- src/main/java/com/shaft/validation/JsonValidationsBuilder.java
- src/main/java/com/shaft/validation/ValidationEnums.java
- src/main/java/com/shaft/validation/ValidationHelper.java
- src/main/java/com/shaft/validation/Validations.java
- src/main/java/com/shaft/validation/ValidationsAttributesBuilder.java
- src/main/java/com/shaft/validation/ValidationsBuilder.java
- src/main/java/com/shaft/validation/Verifications.java
- src/main/java/com/shaft/validation/WebBrowserValidationsBuilder.java
- src/main/java/com/shaft/validation/WebElementValidationsBuilder.java
- src/test/java/testPackage01/Test_ValidationsBuilder.java
TODO: playwright element and browser validations
> fluent validations and complete validations revamp

- pom.xml
- src/main/java/com/shaft/api/BrowserStack.java
- src/main/java/com/shaft/api/RestActions.java
- src/main/java/com/shaft/cli/FileActions.java
- src/main/java/com/shaft/cli/TerminalActions.java
- src/main/java/com/shaft/cucumber/ElementSteps.java
- src/main/java/com/shaft/db/DatabaseActions.java
- src/main/java/com/shaft/driver/DriverFactoryHelper.java
- src/main/java/com/shaft/gui/browser/PlayWrightBrowserActions.java
- src/main/java/com/shaft/gui/browser/WebDriverBrowserActions.java
- src/main/java/com/shaft/gui/element/PlayWrightElementActions.java
- src/main/java/com/shaft/gui/element/TouchActions.java
- src/main/java/com/shaft/gui/element/WebDriverElementActions.java
- src/main/java/com/shaft/tools/io/ReportManagerHelper.java
- src/main/java/com/shaft/validation/ValidationHelper.java
- src/main/java/com/shaft/validation/ValidationsAttributesBuilder.java
- src/main/java/com/shaft/validation/ValidationsBuilder.java
- src/test/java/testPackage01/Test_ValidationsBuilder.java
.nested default message under custom log message
.differentiate assertions and verifications
.remove action counter from step name
> reporting enhancements

- pom.xml
- src/main/java/com/shaft/gui/element/ElementActionsHelper.java
> catching element is not interactable exception and version bump

- src/main/java/com/shaft/gui/element/TouchActions.java
> Adding pinchToZoom method

- src/test/java/testPackage01/Test_SelectedValue.java
first PR from codespaces to merge code developed via codespaces
> fixed sample select URLs

- src/main/java/com/shaft/gui/element/WebDriverElementActions.java
- src/main/java/com/shaft/gui/image/ScreenshotManager.java
> removed wrong method, implemented fix for element not found

- src/main/java/com/shaft/api/RequestBuilder.java
- src/main/java/com/shaft/api/RestActions.java
> closing #358

- pom.xml
- src/main/java/com/shaft/tools/listeners/AlterSuiteListener.java
- src/main/java/com/shaft/validation/FileValidationsBuilder.java
- src/main/java/com/shaft/validation/NativeValidationsBuilder.java
- src/main/java/com/shaft/validation/NumberValidationsBuilder.java
- src/main/java/com/shaft/validation/RestValidationsBuilder.java
- src/main/java/com/shaft/validation/Validations.java
- src/main/java/com/shaft/validation/ValidationsBuilder.java
- src/main/java/com/shaft/validation/ValidationsExecutor.java
- src/main/java/com/shaft/validation/WebDriverBrowserValidationsBuilder.java
- src/main/java/com/shaft/validation/WebDriverElementValidationsBuilder.java
- src/main/javadoc/index.html
- src/main/resources/defaultProperties/PlatformFlags.properties
- src/test/java/testPackage01/Test_RetryAnalyzer.java
-implementing retry logic
-configuring default value (disabled)
-updating config manager
-documenting the validations wizard
closes #361
> new logic/docs

- src/main/java/com/shaft/api/RestActions.java
- src/test/java/testPackage01/Test_sendGraphqlRequest.java
> Support for Sending GraphQl API Request

- src/main/java/com/shaft/gui/video/RecordManager.java
Android Video Encoding Optimisation
> Android Video Encoding Optimization

- src/main/java/com/shaft/gui/element/ElementActions.java
- src/test/java/testPackage01/Test_uploadFile.java
- Add a condition to check if the relative path starts with "src"
- Remove deprecated methods from Test_uploadFile test class
> Enhance typeFileLocationForUpload To Auto Detect Relative Path

- src/main/java/com/shaft/api/BrowserStack.java
- src/main/java/com/shaft/driver/DriverFactory.java
- src/main/java/com/shaft/gui/element/TouchActions.java
- src/main/resources/defaultProperties/browserStack.properties
- src/test/java/testPackage01/Test_google.java
- src/test/java/testPackage01/appium/AndroidBasicInteractionsTest.java
- tested and working on emulator and real physical device for the following configurations
-- screen scroll up and down
-- nested element scroll up and down
-- nested element scroll left and right
- fixed issue with browserStack properties
> custom algorithm for nested element scrolling

- src/main/java/com/shaft/tools/io/PropertyFileManager.java
removed the following 
System.setProperty("forceCheckForElementVisibility", String.valueOf(false));
System.setProperty("forceCheckElementLocatorIsUnique", String.valueOf(false));
System.setProperty("forceCheckTextWasTypedCorrectly", String.valueOf(false));
> removed 3 props. from mangeMaxPerformanceMode class

- src/main/java/com/shaft/gui/element/AlertActions.java
- src/main/java/com/shaft/gui/element/ElementActions.java
- src/test/java/testPackage01/TestJSAlertBox.java
- src/test/java/testPackage01/TestJSConfirmBox.java
- src/test/java/testPackage01/TestJSPromptBox.java
- AlertActions class added for handling JS browser alerts
- performAlertAction method added to ElementActions class
- Test case added in separate classes for each type of alert [Box, Confirm, Prompt]
> Alert actions

- pom.xml
- src/main/java/com/shaft/api/RestActions.java
- src/main/java/com/shaft/gui/element/ElementActions.java
- src/main/java/com/shaft/gui/element/ElementActionsHelper.java
- src/main/java/com/shaft/gui/element/TouchActions.java
- src/main/java/com/shaft/gui/element/WebDriverElementActions.java
- src/main/java/com/shaft/gui/image/ImageProcessingActions.java
- src/main/java/com/shaft/gui/image/ScreenshotManager.java
- src/main/java/com/shaft/tools/io/ReportManagerHelper.java
- src/main/java/com/shaft/tools/listeners/AlterSuiteListener.java
- src/main/resources/defaultProperties/internal.properties
- src/test/java/testPackage01/appium/AndroidBasicInteractionsTest.java
. AlterSuiteListener:
.. Early loading OpenCV once to get some performance gains.
. AndroidBasicInteractionsTest:
.. Optimizing imports
. ElementActions:
.. remove static modifier from public AlertActions performAlertAction()
. ElementActionsHelper:
.. implement custom explicit wait for visually identifiable elements List<Object> waitForElementPresence(WebDriver driver, String elementReferenceScreenshot)
. ImageProcessingActions:
.. complete revamp for the element identification algorithms used in this method List<Integer> findImageWithinCurrentPage(String referenceImagePath, byte[] currentPageScreenshot)
. internal.properties:
.. version bump
. pom/xml:
.. version bump
. ReportManagerHelper:
.. fixed issue related to failing to make allure executable on unix-based shells while executing …
> Various changes related to AI

- src/main/javadoc/index.html
- src/main/resources/defaultProperties/JiraXRay.properties
- src/main/resources/defaultProperties/pattern.properties
- Add XRay plugin configurations to configuration manager page.
- Comment 'allure.link' patterns properties from pattern.properties file.
- Add 'allure.link.tms.pattern' and 'allure.link.custom.pattern' properties to JiraXray.properties file
> Add XRay tab to Configuration Manager

- src/main/java/com/shaft/api/RestActions.java
- src/test/java/unitTests/tests_restActions.java
Added **getResponseJSONValueFromList** static method in **RestActions** class
And added a test case for it in **tests_restActions** class
> Add getResponseJSONValueFromList method

- src/main/java/com/shaft/driver/DriverFactoryHelper.java
> fixes #612

- src/main/java/com/shaft/gui/element/TouchActions.java
- src/test/java/testPackage01/Test_SwipeElementIntoView.java
1- Fix issue #641 Element locator is NULL by make internalScrollableElementLocator can be null and the condtion become 'OR' not 'AND'
2- Add Test_SwipeElementIntoView class  to test the swipeElementIntoView function
> 1- Fix issue #641 , 2- Add Test_SwipeElementIntoView class to test the swipeElementIntoView function

- src/main/java/com/shaft/api/RestActions.java
- src/test/java/testPackage01/SHAFTWizard/Test_Wizard_API.java
- Apply the fix for JSON path data type value bug
- Added two new cases
> Fix the JSON path data type value bug

- pom.xml
- src/main/java/com/shaft/driver/SHAFT.java
- src/main/java/com/shaft/tools/io/YAMLFileManager.java
- src/test/java/testPackage01/Test_YAMLFileManager.java
- src/test/resources/testDataFiles/yaml/yaml_test_data.yaml
Adding support to read YAML files as test data
> Adding support to read YAML files as test data

- .github/workflows/test.yml
- .github/workflows/test_mobile.yml
- src/main/java/com/shaft/gui/browser/WebDriverBrowserActions.java
- src/main/java/com/shaft/gui/element/ElementActionsHelper.java
- src/main/java/com/shaft/gui/element/TouchActions.java
- src/main/java/com/shaft/gui/element/WebDriverElementActions.java
one more core change, no more driver.findElement in the elementActions.
> Tighter waits

- src/main/java/com/shaft/api/RestActions.java
- src/main/java/com/shaft/driver/SHAFT.java
**Note**: Could not add a tests for this as i can't find any demo apis that have mandatory cookies in the request.
But here's a screenshot of the debugger for verification
> Support Add Cookie directly without request method

- src/main/java/com/shaft/tools/listeners/CucumberFeatureListener.java
- src/main/java/com/shaft/tools/listeners/CucumberTestRunnerListener.java
- src/main/java/com/shaft/tools/listeners/InvokedMethodListener.java
ElementActions.switchToDefaultContent();
> remove unneeded reset default content

- src/main/java/com/shaft/driver/DriverFactoryHelper.java
- Remove the setFtpProxy settings
- Change proxy settings variable name
> Proxy settings fix

- src/main/java/com/shaft/tools/io/ReportManagerHelper.java
> fixed issue by overriding hardcoded java_home system variable (if any)

- src/main/java/com/shaft/gui/browser/WebDriverBrowserActions.java
- src/main/javadoc/index.html
- src/main/resources/defaultProperties/WebCapabilities.properties
- src/test/java/testPackage01/validationsWizard/Test_URLNavigation.java
> Feature#794

- pom.xml
- src/main/java/com/shaft/driver/SHAFT.java
- src/main/java/com/shaft/gui/element/ElementActions.java
- src/main/java/com/shaft/gui/element/TouchActions.java
- src/main/java/io/github/shafthq/shaft/gui/element/ElementActionsHelper.java
- src/main/java/io/github/shafthq/shaft/gui/element/FluentElementActions.java
- src/main/java/io/github/shafthq/shaft/gui/image/ImageProcessingActions.java
- src/main/java/io/github/shafthq/shaft/gui/image/ScreenshotManager.java
- src/main/java/io/github/shafthq/shaft/gui/locator/Locator.java
- src/main/java/io/github/shafthq/shaft/gui/locator/LocatorBuilder.java
- src/main/java/io/github/shafthq/shaft/validations/helpers/ValidationsBuilder.java
- src/main/java/io/github/shafthq/shaft/validations/helpers/ValidationsHelper.java
- src/main/resources/properties/default/internal.properties
- src/test/java/testPackage01/locator/LocatorBuilderTest.java
- enhancements to click, clickAndHold to handle element not intractable exception properly
- enhancements to reporting to handle relative locators
- centralized locator name formatting
- put back "waitForElementToBePresent" and flag as Deprecated as it was renamed without prior notice
- The new locator package with the locator builder classes
- new BETA testPackage01.locator.LocatorBuilderTest test class
- fixed issue with lack of element highlighting in case of using relative locator
> introducing the new Locator Builder 🎉🎉🎉

- src/main/java/com/shaft/driver/DriverFactory.java
- src/main/java/io/github/shafthq/shaft/listeners/TestNGListener.java
- src/main/java/io/github/shafthq/shaft/listeners/helpers/CucumberHelper.java
- src/main/java/io/github/shafthq/shaft/properties/Mobile.java
- src/main/java/io/github/shafthq/shaft/properties/PropertiesHelper.java
- src/main/java/io/github/shafthq/shaft/properties/PropertyFileManager.java
- src/test/java/testPackage/appium/AndroidBasicInteractionsTest.java
> property manager related fixes

- src/main/java/com/shaft/gui/browser/BrowserActions.java
- src/main/java/io/github/shafthq/shaft/gui/browser/FluentBrowserActions.java
- src/test/java/testPackage/Test_Cookies.java
Add cookie support #755 
Methods added with docs:
- addCookie
- getCookie
- getAllCookies
- getCookieDomain
- getCookieValue
Test Class Test_Cookies added.
> Add Cookies support &  Tests

- .gitignore
- pom.xml
- src/main/java/com/shaft/api/RestActions.java
- src/main/java/com/shaft/cli/TerminalActions.java
- src/main/java/com/shaft/gui/element/ElementActions.java
- src/main/java/com/shaft/gui/element/TouchActions.java
- src/main/java/io/github/shafthq/shaft/driver/DriverFactoryHelper.java
- src/main/java/io/github/shafthq/shaft/gui/element/ElementActionsHelper.java
- src/main/java/io/github/shafthq/shaft/listeners/helpers/TestNGListenerHelper.java
- src/main/java/io/github/shafthq/shaft/properties/PropertiesHelper.java
- src/main/java/io/github/shafthq/shaft/tools/io/helpers/LogRedirector.java
- src/main/java/io/github/shafthq/shaft/tools/io/helpers/ReportHelper.java
- src/main/java/io/github/shafthq/shaft/tools/io/helpers/ReportManagerHelper.java
- src/main/resources/docker-compose/start_emu_headless
- src/main/resources/properties/default/Reporting.properties
- src/main/resources/properties/default/internal.properties
- src/main/resources/properties/default/log4j2.properties
- src/test/java/testPackage/appium/AndroidBasicInteractionsTest.java
https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md
> append flags

- src/main/java/com/shaft/gui/element/ElementActions.java
getElementsCount
waitForElementToBeReady
> Return deleted static methods

- src/main/java/io/github/shafthq/shaft/validations/helpers/RestValidationsBuilder.java
- src/main/java/io/github/shafthq/shaft/validations/helpers/ValidationsExecutor.java
- src/test/java/testPackage/unitTests/Tests_Api.java
Solving #804 to be able to assert on a response json list directly.
> API validation extractedJsonValueAsList

- .github/workflows/test.yml
- .github/workflows/test_mobile.yml
Reference: https://github.com/marketplace/actions/publish-test-results
> Pipeline Publish Test Results

- src/main/java/com/shaft/gui/element/ElementActions.java
waitForElementToBePresent hot fix (#864 & #863)
> waitForElementToBePresent hot fix (#864 & #863)

- src/main/java/com/shaft/gui/element/ElementActions.java
- src/main/java/io/github/shafthq/shaft/gui/element/ElementActionsHelper.java
This should better handle the waitForElementToBePresent method conditions and fix the failing pipeline tests.
> waitForElementToBePresent enhancements & exception handling

- src/main/java/com/shaft/api/BrowserStack.java
- src/main/java/io/github/shafthq/shaft/properties/BrowserStack.java
- src/main/resources/properties/default/browserStack.properties
Details: https://github.com/ShaftHQ/SHAFT_ENGINE/issues/880
> implement browserstack userProvidedCustomID

- src/main/java/io/github/shafthq/shaft/gui/element/FluentElementActions.java
- src/test/java/testPackage/SHAFTWizard/Test_Wizard_GUI.java
Click using Javascript only and sample test case added
> click using javascript

- src/test/java/testPackage/BigPageActionsTest.java
- src/test/java/testPackage/SwitchToNewTabTest.java
@MahmoudElSharkawy pretty straightforward fix for the broken search locator (magdy was using a css selector in his test so I didn't catch it doing a global file search) and removing two elements that turned out to have dynamic IDs :D 
Feel free to review and merge please. [Last PR of the morning I promise]
> fix broken tests

- src/main/java/io/github/shafthq/shaft/listeners/TestNGListener.java
- src/main/java/io/github/shafthq/shaft/tools/io/ExecutionSummaryReport.java
- src/main/java/io/github/shafthq/shaft/tools/support/HTMLHelper.java
* Add cases (failed & skipped) details & enhancements to Execution Summary Report.
* Test Execution Summary Results now is at the end of the console log.
> Add cases details & enhancements to Execution Summary Report

- src/main/java/io/github/shafthq/shaft/tools/io/ReportHelper.java
- src/main/resources/properties/default/Reporting.properties
Add attachExtentReportToAllureReport property and it's false by default as it consumes alot of space as discussed in the Slack channel.
> Add attachExtentReportToAllureReport property

- src/main/java/io/github/shafthq/shaft/listeners/TestNGListener.java
- src/main/java/io/github/shafthq/shaft/tools/io/ExecutionSummaryReport.java
- src/main/java/io/github/shafthq/shaft/tools/support/HTMLHelper.java
Based on the feedback from different teams, I
* Added the passed status to the report
* Added search bar to search for the cases inside the table
* Added  status dropdown list to filter the table by the status
> Add Search and Filter to the Execution Summary Report

- src/main/java/io/github/shafthq/shaft/driver/DriverFactoryHelper.java
- src/main/java/io/github/shafthq/shaft/gui/browser/FluentBrowserActions.java
- src/main/java/io/github/shafthq/shaft/gui/image/ScreenshotManager.java
- src/main/java/io/github/shafthq/shaft/properties/Internal.java
- src/main/java/io/github/shafthq/shaft/properties/Properties.java
- src/main/java/io/github/shafthq/shaft/properties/PropertiesHelper.java
- src/main/resources/properties/default/internal.properties
here are the screenshots of chrome, firefox and Safari browsers
> Fix Bug #960 and enhance overlay images

- src/main/java/io/github/shafthq/shaft/listeners/TestNGListener.java
- src/main/java/io/github/shafthq/shaft/tools/io/ExecutionSummaryReport.java
- src/main/java/io/github/shafthq/shaft/tools/support/HTMLHelper.java
> Add error message to Execution Summary Report table

- src/main/java/io/github/shafthq/shaft/listeners/TestNGListener.java
- src/main/java/io/github/shafthq/shaft/listeners/TestNGListenerHelper.java
- src/main/java/io/github/shafthq/shaft/tools/io/ExecutionSummaryReport.java
- src/main/java/io/github/shafthq/shaft/tools/io/ReportManagerHelper.java
- src/main/java/io/github/shafthq/shaft/tools/support/HTMLHelper.java
> Add Execution Summary Report logo, validations and issue summary

- src/main/java/io/github/shafthq/shaft/tools/io/ExecutionSummaryReport.java
- src/main/java/io/github/shafthq/shaft/tools/io/ReportManagerHelper.java
- src/main/java/io/github/shafthq/shaft/tools/support/HTMLHelper.java
> Execution Summary Report Issue Summary enhancements

- src/main/java/io/github/shafthq/shaft/gui/element/ElementActionsHelper.java
- src/main/java/io/github/shafthq/shaft/gui/element/FluentElementActions.java
- src/main/java/io/github/shafthq/shaft/tools/support/HTMLHelper.java
- src/test/java/testPackage/validationsWizard/Test_AttributeWait.java
Add waitToAttribute and waitForElementAttributeToBe to support the element waiting for an attribute to be a specific value.
> Waiting for attribute

- src/main/java/io/github/shafthq/shaft/listeners/TestNGListenerHelper.java
- src/main/resources/k8s/k8s.md
- src/main/resources/k8s/selenium-grid-chrome-scaledobject.yaml
- src/main/resources/k8s/selenium-grid-edge-scaledobject.yaml
- src/main/resources/k8s/selenium-grid-firefox-scaledobject.yaml
- src/test/java/testPackage/SHAFTWizard/ThreadSafeGuiWizardTests.java
creating a guide for initializing an auto-scalable self-healing k8s KEDA powered selenium grid for chrome, firefox, and edge.
simply follow the steps in the readme.md file and you'll end up with a fully functional auto-scalable selenium grid cluster
> auto-scalable self-healing k8s

- pom.xml
- src/main/resources/properties/default/internal.properties
will impact
--plugin com.shaft.listeners.CucumberFeatureListene
com.shaft.listeners.TestNGListener
and
com.shaft.listeners.CucumberTestRunnerListener
> Release prep 20230328

- src/main/java/com/shaft/gui/element/internal/ElementActionsHelper.java
> Add element actions page source attachment in failure

- src/main/java/com/shaft/gui/element/internal/ElementActionsHelper.java
- src/main/java/com/shaft/properties/internal/Visuals.java
- src/main/java/com/shaft/validation/internal/ValidationsHelper.java
- src/main/javadoc/index.html
- src/main/resources/properties/default/VisualValidations.properties
* Created new page Source section in the configurations manager
* New whenToTakePageSourceSnapshot property in the VisualValidations.properties and dded them to the visuals class
> Create configurable Page Source attachment for WebDriver

- src/main/java/com/shaft/tools/internal/support/HTMLHelper.java
Fixes #1029 
https://user-images.githubusercontent.com/46620378/230315016-e828aba2-500f-43fc-8de4-3aae9a4fc652.mp4
> Execution Summary Report status filter fix

- pom.xml
- src/main/java/com/shaft/properties/internal/Internal.java
@MahmoudElSharkawy if it's confirmed that this is the issue then merge this PR to get a new release.
> Fixing build issue

- src/main/java/com/shaft/gui/element/internal/FluentElementActions.java
- src/test/java/testPackage/mockedTests/MultipleElementsFailureTest.java
- src/test/java/testPackage/mockedTests/NoSuchElementFailureTest.java
fixing clickUsingJavascript failure reporting and adding related tests
> fixing clickUsingJavascript failure reporting

- src/main/java/com/shaft/gui/element/internal/ElementActionsHelper.java
- will attempt to move to element after scrolling it into view.
- will attempt to click using native selenium.
- will attempt to click using actions library (different algorithm) and native selenium
- will attempt javascript click
- will output more logs for the untraditional click attempts.
> click action enhancements

- .github/workflows/e2eTests.yml
- src/main/java/com/shaft/gui/element/internal/ElementActionsHelper.java
Browser stack extended and upgraded their sponsored licence to x5 parallel runs.
> Parallelizing BStacktests

- src/main/java/com/shaft/gui/browser/internal/FluentBrowserActions.java
- should fix the duplicated "pass" report message upon successful navigation
- reduces overall lines of code
- reduces code complexity
> navigation logical revamp

- src/main/java/com/shaft/driver/internal/DriverFactoryHelper.java
- src/main/java/com/shaft/gui/browser/internal/BrowserActionsHelpers.java
- src/main/java/com/shaft/properties/internal/Reporting.java
removing final page snapshot creation and usage
> removing final page snapshot 

- src/main/java/com/shaft/gui/internal/locator/LocatorBuilder.java
- src/main/java/com/shaft/gui/internal/locator/XpathAxis.java
- src/test/java/testPackage/locator/LocatorBuilderTest.java
```java
@Test
public void axisBy_followingSibling() {
By locator = Locator.hasTagName("h1").hasText("SHAFT User Guide").axisBy().followingSibling("p").build();
driver.assertThat().element(locator).text().contains("Stop reinventing the wheel.").perform();
}
@Test
public void axisBy_chain_precedingSibling() {
By locator = Locator.hasTagName("h1").hasText("SHAFT User Guide").axisBy().followingSibling("p").axisBy().precedingSibling("h1").build();
driver.assertThat().element(locator).text().isEqualTo("SHAFT User Guide").perform();
}
```
supports the following axis types:
- `following-sibling`
- `preceding-sibling`
- `ancestor`
- `descendant`
- `following`
- `preceding`
> implementing axisBy

- src/main/java/com/shaft/gui/element/internal/FluentElementActions.java
- src/test/java/testPackage/SHAFTWizard/GUIWizardTests.java
updating variable name and method description
> updating select method

- src/main/java/com/shaft/listeners/TestNGListener.java
- src/main/java/com/shaft/properties/internal/Reporting.java
- src/main/java/com/shaft/tools/io/internal/ReportManagerHelper.java
Small PR to implement the feature #1113
> Small PR to implement the feature

- .github/workflows/codeql-analysis.yml
- .github/workflows/e2eTests.yml
- .github/workflows/mavenCentral_cd.yml
- cleaning unused code for maven central pipeline
- fixing codeQL pipeline
- sequentializing lambatest jobs
> updating pipelines:

- pom.xml
- src/main/java/com/shaft/gui/element/internal/ElementActionsHelper.java
- src/main/java/com/shaft/properties/internal/Flags.java
- src/main/java/com/shaft/properties/internal/Internal.java
- src/test/java/testPackage/properties/FlagsTests.java
type method enhancement 
adding attemptToClickBeforeTyping flag
> Beta Version Release

- src/main/java/com/shaft/gui/browser/internal/FluentBrowserActions.java
- src/main/java/com/shaft/properties/internal/Web.java
- src/test/java/testPackage/SwitchToNewTabTest.java
- src/test/java/testPackage/properties/PlatformTests.java
- src/test/java/testPackage/properties/WebTests.java
now you can navigate in a new window or a new tab
> enhance navigate to url

- .github/workflows/e2eTests.yml
!%regex[.*NetworkInterceptionTest.*],
> Disabling mocking test

- src/main/java/com/shaft/tools/io/internal/ExecutionSummaryReport.java
Fix Execution summary report issue #1224
> Fix ExecutionSummaryReport

- src/main/java/com/shaft/gui/element/internal/ElementActionsHelper.java
- src/main/java/com/shaft/gui/internal/image/ScreenshotManager.java
- src/main/java/com/shaft/gui/internal/video/RecordManager.java
- src/test/java/testPackage/BigPageActionsTest.java
now user can change visual properties during run time as most of other properties .
> updating Screenshot Manager

- src/main/java/com/shaft/api/RequestBuilder.java
- src/main/java/com/shaft/api/RestActions.java
- src/main/java/com/shaft/driver/SHAFT.java
[#1223][[13.8.2023][Solving  issue useRelaxedHTTPSValidation - SSLException]
> [13.8.2023][#1223][Solving  issue useRelaxedHTTPSValidation - SSLException]

- src/main/java/com/shaft/driver/internal/DriverFactoryHelper.java
fixing auto maximization issue
> fixing auto maximization issue

- pom.xml
- src/main/java/com/shaft/properties/internal/Internal.java
Release for the auto maximize hot fix.
> Release 7.3.20230824

- pom.xml
- src/main/java/com/shaft/gui/browser/internal/BrowserActionsHelpers.java
- src/main/java/com/shaft/properties/internal/Internal.java
- src/main/java/com/shaft/tools/io/internal/FailureReporter.java
fixes https://github.com/ShaftHQ/SHAFT_ENGINE/issues/1244
Will release a new build after merging :D
> Navigation fix

- .github/workflows/e2eTests.yml
> update e2e tests

- src/main/java/com/shaft/driver/internal/DriverFactoryHelper.java
- src/main/java/com/shaft/gui/internal/image/ScreenshotManager.java
- src/main/java/com/shaft/listeners/CucumberFeatureListener.java
- src/test/java/mockito/DatabaseActionsTests.java
attempting to use mockito to perform mocked database unit tests
> Databsemockedtests

- src/main/java/com/shaft/gui/element/TouchActions.java
- Enhancement of the swipeElementIntoView(String targetText)  method to be swipeElementIntoView(String targetText,SwipeMovement movement)
- Add TouchActions.rotate method
> Enhancement of the swipeElementIntoView by string text method & Add touch actions.rotate method 

- src/main/java/com/shaft/tools/internal/support/HTMLHelper.java
-Adding hints for "Validations" and "Issues"
-Renaming the "Issues" categorization
-Changing "Total Cases" to "Total Tests"
> Execution Summary Report Enhancements

- src/main/java/com/shaft/tools/internal/support/HTMLHelper.java
Added info icons to be displayed when hovering on to describe some not very clear to the stakeholders information.
> Enhance the Execution summary report readability

- src/main/java/com/shaft/properties/internal/PropertiesHelper.java
Reverts ShaftHQ/SHAFT_ENGINE#1406
> Revert "overriding forced flags for mobile execution"

- src/main/java/com/shaft/driver/SHAFT.java
- src/main/java/com/shaft/driver/internal/FluentWebDriverAction.java
- src/main/java/com/shaft/gui/waits/WaitActions.java
- src/test/java/testPackage/mockedTests/WaitActionsTest.java
- will only initialize with existing helper instance
- ensures running on the same active browser instance
- added tests for ExpectedConditions and LambdaExpressions
> fixed wait action initialization

- src/main/java/com/shaft/driver/DriverFactory.java
- src/main/java/com/shaft/driver/internal/DriverFactory/BrowserStackHelper.java
- src/main/java/com/shaft/driver/internal/DriverFactory/DriverFactoryHelper.java
- src/main/java/com/shaft/driver/internal/DriverFactory/LambdaTestHelper.java
- encapsulate and optimize structure
> create helper classes

- src/main/java/com/shaft/tools/io/internal/AttachmentReporter.java
- src/main/java/com/shaft/tools/io/internal/ReportManagerHelper.java
- AttachementReporter Class Added containing the newly added logic for handling attachments
- Some Enhancements are made to the logic :
1- LinkedHashMap is now used instead of HashMap
2- Switch case now switches over the LinkedHashMap key instead of the AttachementType for better consistency
3- Get Attachment Case now returns  empty string ("") for better readability
> Added new separate class for handling attachments

- src/main/java/com/shaft/driver/internal/DriverFactory/BrowserStackHelper.java
- src/main/java/com/shaft/properties/internal/BrowserStack.java
- browserStack.enableBiometric
- browserStack.debug => enables interactive debugging
- upgrading selenium and appium versions
> adding new properties

- .github/workflows/e2eTests.yml
- pom.xml
- src/main/java/com/shaft/properties/internal/Internal.java
- src/test/java/testPackage/legacy/BrowserStackTests.java
- src/test/java/testPackage/legacy/FrameTests.java
- src/test/java/testPackage/legacy/SearchOptimizationTest.java
- src/test/java/testPackage/legacy/WaitActionsTests.java
- src/test/java/testPackage/locator/LocatorBuilderTest.java
- src/test/resources/CucumberFeatures/SHAFT_BDD_Sample_EN.feature
fix failing tests (user guide homepage upgrade)
release prep
> 8.2.20240411

- src/main/java/com/shaft/gui/element/internal/Actions.java
> Fix some element actions not taking screenshot in case of param screenshotParamsWhenToTakeAScreenshot=Always

- src/main/java/com/shaft/gui/element/internal/Actions.java
Handle scrolling with isMobileNativeExecution which broke mobile native new-action-core events.
> 1838 bug clicktap method is not working in release 8420241024

- .github/workflows/e2eTests.yml
- src/main/java/com/shaft/properties/internal/BrowserStack.java
- src/test/java/testPackage/appium/MobileWebTest.java
- src/test/java/testPackage/resettingCapabilitiesIssue/UploadFileTests.java
-update default browserstack selenium version
-update default browserstack appium version
-update property name for mobile browser in pipeline file -comment some code in MobileWebTest file
> remote mobile/web execution fixes:

- pom.xml
- src/main/java/com/shaft/properties/internal/Internal.java
> 9.1.20250203

- src/main/java/com/shaft/api/RequestBuilder.java
- src/test/java/com/shaft/api/ApiPerformanceReportTest.java
- src/test/java/customCucumberSteps/steps.java
- src/test/java/testPackage/SHAFTWizard/APIWizardTests.java
- src/test/java/testPackage/SHAFTWizard/GUIWizardTests.java
- src/test/java/testPackage/legacy/GoogleTests.java
- src/test/java/testPackage/legacy/SearchOptimizationTest.java
- src/test/java/testPackage/mockedTests/CoverageTests.java
- src/test/java/testPackage/resettingCapabilitiesIssue/UploadFileTests.java
- src/test/resources/CucumberFeatures/SHAFT_BDD_Sample_EN.feature
- src/test/resources/CustomCucumberFeatures/googleTest.feature
- **5 Passed**   
- **Status:** 🟢 Pass (No Fixes)  
- **Commented Out The Code that Appends Query Paramater because RestAssured Handles That Automatically**  
- `prepareRequestURLWithParameters();`  
- **Converted the Api Object to ThreadLocal to prevent Parallel Execution Issues that took place at :**
- `APIWizardTests.java`  
- **51 Passed**   
- **5 Skipped**  
- **Final Status:** 🟢 Pass  
- **Disabled due to Google Captcha:**  
- `searchForQueryandAssertResultsNumDisplayed` - `testPackage.legacy.GoogleTests`  
- `website` - `testPackage.legacy.SearchOptimizationTest`  
- `submitFormUsingJavaScript` - `testPackage.mockedTests.CoverageTests`  
- `test` - `testPackage.SHAFTWizard.GUIWizardTests`  
- **Disabled due URL is broken:**  
- …
> Fix pipeline tests

- src/main/java/com/shaft/tools/io/CSVFileManager.java
- src/test/java/testPackage/legacy/CSVFileManagerTest.java
Adding getFirstColumn,MaxCell , MinCell and Column count and their comments
> Updating CSVFileManager

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
make items as header in markdown instead of making it bold
> docs: enhance issue template 

- src/main/java/com/shaft/gui/element/internal/Actions.java
to differentiate between new and suppressed exceptions
> Improve exception handling in Actions.java
