src/main/java/com/shaft/api/RestActions.java

Handled the ClassCastException which was thrown when passing xml/json path that has different format or different separator than "." in the getResponseXMLValue / getResponseXMLValueAsList / getResponseJSONValue /getResponseJSONValueAsList methods in the RestActions class.

Reporting fix

---

src/main/java/com/shaft/tools/support/JavaActions.java

Cast all numeric values to String in AssertEquals method in case of sensitive literal equivalence (in both true and false cases)

Cast all numeric values to String in AssertEquals method in case of

---

.github/workflows/test.yml
src/main/java/com/shaft/tools/io/PropertyFileManager.java
src/main/javadoc/index.html
src/main/resources/defaultProperties/PlatformFlags.properties

Enable the maximum performance mode but without the headless execution.
**Ticket #241**

Enable the maximum performance mode with and without the headless execution

---

src/main/java/com/shaft/validation/Assertions.java
src/main/java/com/shaft/validation/Verifications.java
src/test/java/unitTests/tests_validations_assertions.java

**Changes**: 
* public enum ElementAttributeType in both Assertions and Verifications classes
*  Implement an overloaded methods to take these enums for the common attributes or a string for any other needed attribute.
* Added a unit testing case to test the ElementAttributeType method.

Added ElementAttributeType enums for the ValidateElementAttribute methods (#76)

---

src/main/java/com/shaft/validation/Assertions.java
src/main/java/com/shaft/validation/Verifications.java

**Changes**
* Added public enum BrowserAttributeType in both Assertions and Verifications classes
* Implemented an overloaded methods to make use of these enums attribute and left the old methods unchanged.

Add enums for the verify/assertBrowserAttribute method #299

---

pom.xml
src/main/java/com/shaft/gui/element/TouchActions.java
src/main/resources/defaultProperties/internal.properties
src/test/java/testPackage01/appium/AndroidBasicInteractionsTest.java

These methods were upgraded to be W3C compliant:
- tap(By elementLocator)
- doubleTap(By elementLocator)
- longTap(By elementLocator)
- swipeToElement(By sourceElementLocator, By destinationElementLocator)
- swipeByOffset(By elementLocator, int xOffset, int yOffset)
- swipeElementIntoView(By targetElementLocator, SwipeDirection swipeDirection)
Created this new method:
- swipeElementIntoView(By scrollableElementLocator, By targetElementLocator, SwipeDirection swipeDirection)
Deprecated the following methods:
- swipeElementIntoView(By targetElementLocator, SwipeDirection swipeDirection, SwipeTechnique swipeTechnique)
- swipeElementIntoView(By targetElementLocator, SwipeDirection swipeDirection, SwipeTechnique swipeTechnique, int scrollableElementInstanceNumber)

replacing all deprecated TouchAction calls with W3C compliant Actions

---

src/main/java/com/shaft/gui/element/TouchActions.java
src/test/java/testPackage01/appium/AndroidBasicInteractionsTest.java

- fixing issue whereby SHAFT fails to find the element if at the end of the current screen or scrollable element view
- handling different cases per swipe direction on main application screen (up, down, left, right)
- testing screen scroll vertically up and down
- testing nested element scroll vertically up and down
- testing nested element scroll horizontally up and down

optimizing w3c compliant scroll

---

pom.xml
src/main/java/com/shaft/cucumber/BrowserSteps.java
src/main/java/com/shaft/gui/image/ImageProcessingActions.java
src/main/java/com/shaft/tools/io/LogsHelper.java
src/main/java/com/shaft/tools/io/ReportManagerHelper.java
src/main/java/com/shaft/tools/listeners/AlterSuiteListener.java
src/main/java/com/shaft/tools/listeners/CucumberFeatureListener.java
src/main/java/com/shaft/tools/listeners/CucumberTestRunnerListener.java
src/main/java/com/shaft/tools/listeners/InvokedMethodListener.java
src/main/java/com/shaft/tools/support/JavaActions.java
src/main/resources/defaultProperties/cucumber.properties
src/test/java/customCucumberSteps/steps.java
src/test/java/testPackage01/Test_Healenium.java
src/test/resources/CucumberFeatures/SHAFT_BDD_Sample_EN.feature
src/test/resources/CustomCucumberFeatures/googleTest.feature

. AlterSuiteListener
- optimize imports
- remove unused listener implementation
- remove SHAFT prefix from all test suites/cases
- fix added listeners
- remove discrete log messages
. BrowserSteps
- optimize imports and remove deprecated method
. cucumber.properties
- major refactor with new default values
. CucumberFeatureListener
- new custom plugin to run feature files directly
. CucumberTestRunnerListener
- enhanced custom listener to run using a cucumber test runner class
. ImageProcessingActions
- resolved OpenCV initialization throwable by force switching to JavaScript for element highlighting
. InvokedMethodListener
- exposed some methods to be used in the new plugins
. JavaActions
- created "removeSpecialCharacters" method to be used to process screenshot images file names
. …

created the new custom cucumber listener

---

src/main/java/com/shaft/gui/element/ElementActions.java

Enhance usability for waitForElementToBePresent method by creating overloaded methods **waitForElementToBeReady**  & **waitForElementToBeInvisible** that support both static and wizard implementations.
Also deprecated the public waitForElementToBePresent method to use the new ones.

Enhance usability for waitForElementToBePresent method

---

src/main/java/com/shaft/tools/tms/XrayIntegrationHelper.java
src/main/javadoc/index.html

- Update the Xray helper class to handle _bearer token_ auth instead of supporting _Basic_ only.  
- Enhance the Xray tab on the configuration manager to cover the changes.

Cover bearer token authorization on the XRay integration

---

src/main/java/com/shaft/api/BrowserStack.java
src/main/java/io/github/shafthq/shaft/driver/DriverFactoryHelper.java
src/main/java/io/github/shafthq/shaft/listeners/helpers/TestNGListenerHelper.java

- upgrading browserstack class to use shaft properties manager
- initializing target browser name with empty string to avoid null exception (while attempting to get current element name for enhanced logging) closes #836
- enhancing log message to show successfully opened native android/ios app instead of the generic log message.
- commented cosmetic enhanced reporting feature which overrides certain properties. Closes #839

fixing issue with native app browserstack

---

src/main/java/io/github/shafthq/shaft/tools/io/helpers/ReportManagerHelper.java

Fix the issue of the report on mac
There were actually two things :- 
1- First of all it was CD'ing to generate_allure_report.sh which is No such file or directory so I changed the '' to "" 
After the Fix 
2- The other thing and the one that caused the issue is $parent_path this variable was read as String so it couldn't be appended the variable value well
And here is the generate_allure_report.sh After generation

Fix the issue of the report on mac Bug#858

---

src/main/java/io/github/shafthq/shaft/gui/element/ElementActionsHelper.java
src/main/java/io/github/shafthq/shaft/gui/element/FluentElementActions.java

- Add isElementDisplayed & isElementClickable to FluentElementActions
- Handle scrollToElement InvalidArgumentException exception on Firefox

Migrate static methods to FluentElementActions & Handle scrollToElement exception on Firefox

---

src/main/java/io/github/shafthq/shaft/enums/Screenshots.java
src/main/java/io/github/shafthq/shaft/gui/browser/FluentBrowserActions.java
src/main/java/io/github/shafthq/shaft/gui/element/ElementActionsHelper.java
src/main/java/io/github/shafthq/shaft/gui/element/FluentElementActions.java
src/main/java/io/github/shafthq/shaft/gui/image/ScreenshotHelper.java
src/main/java/io/github/shafthq/shaft/gui/image/ScreenshotManager.java
src/main/java/io/github/shafthq/shaft/tools/io/helpers/ReportManagerHelper.java
src/test/java/testPackage/mockedTests/PageScreenshotTest.java

Details:
https://github.com/ShaftHQ/SHAFT_ENGINE/issues/899
Start Here:
https://github.com/ShaftHQ/SHAFT_ENGINE/pull/915/files#diff-ee7ff917e5146033d294f95c8f8daf2b5212c3593773c5beb239a12e68a82313

implement user triggered screenshots

---

src/main/java/com/shaft/gui/browser/BrowserActions.java
src/main/java/io/github/shafthq/shaft/gui/browser/BrowserActionsHelpers.java
src/main/java/io/github/shafthq/shaft/gui/browser/FluentBrowserActions.java
src/main/java/io/github/shafthq/shaft/gui/image/ScreenshotManager.java

So Basically the issue is on MozillaFirefox specifically , the issue was regarding the height of captured firstImage screenshot 
for some reason - may be update from firefox , I didn't try it on previous versions - after navigation and on pass action method while capturing the first screenshot 
the height appears :- (16) and after scaling (7) then appear at Allure report as described below 
So I first fixed it by setting the height from ScreenShotManager method but I didn't like the fix 
so what I did is I escaped the first screenshot to be taken after the first element action not after the redirection and that fixed the issue as described --> Height at firstImage --> 1560 and after scaling --> 660 then appear at Allure report as described below  
Also Tested Chrome and working as …

Fix the issue of GIF on firefox

---

src/main/java/com/shaft/gui/browser/BrowserActions.java
src/main/java/com/shaft/gui/browser/internal/FluentBrowserActions.java
src/main/java/com/shaft/gui/element/ElementActions.java
src/main/java/com/shaft/gui/element/internal/FluentElementActions.java
src/test/java/testPackage/iFrameTest.java

- switch to iframe should be a browser action not an element action
- Implemented `SwitchToParentFrame()` as it is added as of selenium 4
- Implemented a method to get the current frame name
- Added a test class with the new way by using dummy html so I created an html page that contain parent and 2 children frames to test `switchToParentFrame()` it was great btw enjoyed it :D 
- Refactored this test class as it was outdated and commented `iFrameTest`

Enhance Feature #902

---

src/main/java/com/shaft/driver/internal/DriverFactoryHelper.java
src/main/java/com/shaft/listeners/internal/ConfigurationHelper.java
src/main/java/com/shaft/listeners/internal/CucumberHelper.java
src/main/java/com/shaft/properties/internal/Flags.java

SHAFT.Properties.flags.set().autoCloseDriverInstance(false);
not working on windows due to a chromedriver bug

adding autoclose driver instance

---

src/main/java/com/shaft/properties/internal/Reporting.java
src/test/java/testPackage/properties/ReportingTests.java

- it is not possible to clean the directory before execution, while being inside the execution. therefore it makes no sense to have the ability to set these three properties programatically.

remove the broken feature

---

src/main/java/com/shaft/listeners/TestNGListener.java
src/main/java/com/shaft/listeners/internal/TestNGListenerHelper.java
src/main/java/com/shaft/tools/io/internal/ReportManagerHelper.java

Log finished test information

---

pom.xml
src/main/java/com/shaft/driver/internal/DriverFactoryHelper.java
src/main/java/com/shaft/properties/internal/Flags.java
src/test/java/testPackage/properties/FlagsTests.java

Added a feature to disable cache using flag (disableCache) on the following browsers:
1. Google chrome 
2. Microsoft Edge
3. Firefox
4. Safari
**Note: I could not find a valid website to make a test case for this feature however, this feature was tested locally, and it works fine on mentioned browsers except Safari due to the macOS availability.**
@MahmoudElSharkawy

New feature to disable cache on Firefox, Microsoft Edge and Google chrome browsers

---

src/main/java/com/shaft/gui/element/internal/FluentElementActions.java
src/test/java/testPackage/GetTableRowsDataTests.java

**Purpose** This feature allows users to easily get the rows data for any table that follow the standard html table format: which should have <thead> tag that has all labels in <th> tags and <tbody> which should have all rows in <tr> tags and all the data in <td> tags. for tables. 
**Note** that this feature will only work if the html table follows this standard and does not guarantee results if any tag is missing

Added a feature to get all the rows data for a table

---

pom.xml

Jacoco was broken when this fix for eclipse was implemented.
1. Try to leave the fix and still define argline where it should be.
2. If this fails, will try to remove the argline from testng and junit (but that will break eclipse again)

Attempting to fix jacoco by reversing argline changes

---

.github/workflows/e2eTests.yml
src/main/java/com/shaft/driver/DriverFactory.java
src/main/java/com/shaft/listeners/CucumberTestRunnerListener.java
src/main/java/com/shaft/listeners/JunitListener.java
src/main/java/com/shaft/listeners/TestNGListener.java
src/main/java/com/shaft/listeners/internal/CucumberHelper.java
src/main/java/com/shaft/tools/io/internal/ProjectStructureManager.java
src/test/java/cucumberTestRunner/CucumberTestRunner.java
src/test/java/cucumberTestRunner/CucumberTests.java
src/test/resources/TestSuites/cucumber_testSuite.xml

- If a user wants to run from their testng test runner or command-line argument sometimes they will get NaN on their allure report. They now need to configure their test runner like this file `src/test/java/cucumberTestRunner/CucumberTests.java`
```java
package cucumberTestRunner;
import io.cucumber.testng.AbstractTestNGCucumberTests;
import org.testng.annotations.Listeners;
@Listeners({com.shaft.listeners.TestNGListener.class})
public class CucumberTests extends AbstractTestNGCucumberTests {
}
```
- If a user wants to run a feature file or scenario directly they will now get a log message instructing them to follow the cucumber plugin configuration in this link `https://github.com/ShaftHQ/SHAFT_ENGINE#stop-reinventing-the-wheel-start-using-shaft`
- In all cases

Enhance Cucumber/TestNG user experience:

---

src/main/java/com/shaft/driver/internal/DriverFactoryHelper.java
src/main/java/com/shaft/properties/internal/Paths.java

Fix the download target folder for Firefox and Chromium based browsers.

1299 bug the actual download folder path is not as the path in the properties file

---

pom.xml
src/main/java-mr/21/com/shaft/gui/element/AsyncElementActions.java
src/main/java-mr/21/com/shaft/gui/element/internal/ElementActionsHelper.java
src/main/java/com/shaft/properties/internal/Internal.java
src/test/java/testPackage/BigPageActionsTest.java

- duplicated AsyncElementActions and ElementActionsHelper to be compatible with both JDK 17 and JDK 21.
- set the default to JDK 17, need to test if JDK 21 classes are accessible from a project that uses SHAFT.
- version bump for bug-fix stability maintenance release

multi release jar

---

src/main/java/com/shaft/driver/SHAFT.java
src/main/java/com/shaft/gui/browser/BrowserActions.java
src/main/java/com/shaft/gui/browser/internal/BrowserActionsHelper.java
src/main/java/com/shaft/gui/element/AlertActions.java
src/main/java/com/shaft/gui/element/ElementActions.java
src/main/java/com/shaft/gui/element/internal/ElementActionsHelper.java
src/main/java/com/shaft/gui/waits/WaitActions.java
src/main/java/com/shaft/properties/internal/Timeouts.java

Added some on the most important waits in to the browser and element actions (supporting the fluency wizard) and added a custom method to be used anytime to have the flexibility for creating any custom waits including and & or methods if/when needed by the users.
Usage should be something like this:

Selenium Webdriver Explicit waits wrapping

---

src/main/java/com/shaft/listeners/JunitListener.java
src/main/java/com/shaft/listeners/TestNGListener.java
src/main/java/com/shaft/listeners/internal/TestNGListenerHelper.java
src/main/java/com/shaft/tools/internal/support/HTMLHelper.java
src/main/java/com/shaft/tools/io/internal/ExecutionSummaryReport.java

Add `@TmsLink` &` @Issue` annotation links to the execution summary report.

Execution summary report enhancements

---

src/main/java/com/shaft/listeners/JunitListener.java

- teardown logic was implemented inside the launcherSessionClosed action of JUNit's LauncherSessionListener. This caused several activities to happen multiple times in case of executing several classes.
- moved it to testPlanExecutionFinished trigger in the TestExecutionListener implementation to ensure it runs only once.

moving engine teardown logic

---

src/main/java/com/shaft/properties/internal/PropertiesHelper.java

- this fix defaults turns off the following flags for mobile execution (you can still turn them on in your custom.properties files: --attemptClearBeforeTypingUsingBackspace
--attemptClearBeforeTyping
--clickUsingJavascriptWhenWebDriverClickFails
--forceCheckTextWasTypedCorrectly
--respectBuiltInWaitsInNativeMode
--handleNonSelectDropDown
--validateSwipeToElement
--enableTrueNativeMode (true)

overriding forced flags for mobile execution

---

.github/workflows/e2eTests.yml
src/main/java/com/shaft/driver/internal/DriverFactory/DriverFactoryHelper.java
src/main/java/com/shaft/driver/internal/DriverFactory/OptionsManager.java
src/main/java/com/shaft/properties/internal/Platform.java
src/test/java/junitTestPackage/MoonTests.java
src/test/java/testPackage/mockedTests/MultipleBrowserInstancesTest.java
src/test/java/testPackage/properties/PlatformTests.java

user can now disable BiDi as it conflicts with certain non-standard grid implementations like moon and selenoid
Code: `SHAFT.Properties.platform.set().enableBiDi(false);`
Property file: `enableBiDi=false`
CommandLine: `-DenableBiDi=false`

flagging bidi enablement

---

src/main/java/com/shaft/gui/browser/BrowserActions.java
src/main/java/com/shaft/gui/element/AlertActions.java
src/main/java/com/shaft/gui/element/AsyncElementActions.java
src/main/java/com/shaft/gui/element/ElementActions.java
src/main/java/com/shaft/gui/element/internal/ElementActionsHelper.java
src/main/java/com/shaft/gui/internal/exceptions/MultipleElementsFoundException.java
src/main/java/com/shaft/gui/internal/image/AnimatedGifManager.java
src/test/java/testPackage/SearchOptimizationTest.java
src/test/java/testPackage/mockedTests/CoverageTests.java
src/test/java/testPackage/mockedTests/HoverTests.java

- will now be thrown without waiting for timeout to conclude for all actions that are performed inside the fluent wait block

MultipleElementsFoundException

---

.github/workflows/e2eTests.yml
src/main/java/com/shaft/driver/internal/FluentWebDriverAction.java
src/main/java/com/shaft/gui/browser/BrowserActions.java
src/main/java/com/shaft/gui/browser/internal/BrowserActionsHelper.java
src/main/java/com/shaft/gui/element/AlertActions.java
src/main/java/com/shaft/gui/element/ElementActions.java
src/main/java/com/shaft/gui/element/TouchActions.java
src/main/java/com/shaft/gui/element/internal/ElementActionsHelper.java
src/main/java/com/shaft/gui/internal/image/AnimatedGifManager.java
src/main/java/com/shaft/gui/internal/image/ImageProcessingActions.java
src/main/java/com/shaft/gui/internal/image/ScreenshotHelper.java
src/main/java/com/shaft/gui/internal/image/ScreenshotManager.java
src/main/java/com/shaft/gui/waits/WaitActions.java
src/main/java/com/shaft/listeners/internal/TestNGListenerHelper.java
src/main/java/com/shaft/properties/internal/TestNG.java
src/main/java/com/shaft/tools/internal/support/JavaHelper.java
src/main/java/com/shaft/validation/internal/ValidationsBuilder.java
src/main/java/com/shaft/validation/internal/ValidationsExecutor.java
src/main/java/com/shaft/validation/internal/ValidationsHelper.java
src/main/java/com/shaft/validation/internal/ValidationsHelper2.java
src/test/java/testPackage/ValidationsBuilderTests.java
src/test/java/testPackage/mockedTests/ElementVisibilityTest.java
src/test/java/testPackage/properties/TestNGTests.java
src/test/java/testPackage/validationsWizard/NegativeValidationsTests.java

Assertions are behaving inconsistently and there are several UX issues and potential enhancements.
This PR will be one bulk PR to fix all assertions reporting... Estimated effort (Over 9000!)
here are some samples (before/after)

Testing assertions

---

src/main/java/com/shaft/gui/internal/image/ScreenshotManager.java
src/main/java/com/shaft/tools/io/internal/ReportManagerHelper.java

- screenshots taken for every action
- none of the actions are getting logged in the console

fixed regression issue with screenshots

---

.gitignore
src/main/java/com/shaft/cli/FileActions.java
src/main/java/com/shaft/gui/internal/image/ImageProcessingActions.java
src/main/java/com/shaft/gui/internal/image/ScreenshotHelper.java
src/main/java/com/shaft/tools/io/ReportManager.java
src/main/java/com/shaft/tools/io/internal/ReportManagerHelper.java
src/main/java/com/shaft/validation/internal/ValidationsHelper.java
src/test/java/testPackage/validationsWizard/VisualValidationTests.java
src/test/resources/testDataFiles/src/test/resources/META-INF/services/io.qameta.allure.listener.ContainerLifecycleListener
src/test/resources/testDataFiles/src/test/resources/META-INF/services/io.qameta.allure.listener.FixtureLifecycleListener
src/test/resources/testDataFiles/src/test/resources/META-INF/services/io.qameta.allure.listener.StepLifecycleListener
src/test/resources/testDataFiles/src/test/resources/META-INF/services/io.qameta.allure.listener.TestLifecycleListener
src/test/resources/testDataFiles/src/test/resources/META-INF/services/org.testng.ITestNGListener

Reference image wasn't being read from the correct path in most scenarios causing a false positive or false negative state.

Fix VisualValidations issue

---

src/main/java/com/shaft/driver/internal/DriverFactory/OptionsManager.java
src/main/java/com/shaft/properties/internal/Platform.java
src/main/java/com/shaft/properties/internal/Web.java
src/test/java/testPackage/properties/WebTests.java

~~- Enable BiDi property default value is set to false as it was creating conflicts with session related properties like incognitoMode or setting profiles~~
- incognitoMode property is added for the following browsers:
- Google Chrome
- Microsoft Edge
- Mozilla Firefox

Fix custom options

---

src/main/java/com/shaft/validation/internal/ValidationsHelper2.java

Fix validations section in Execution summary report to show correct number of validations instead of zeroes
[New Reports.zip](https://github.com/user-attachments/files/16576897/New.Reports.zip)

Execution summary report fixes #1680

---

src/main/java/com/shaft/gui/element/internal/Actions.java
src/main/java/com/shaft/properties/internal/Flags.java
src/main/java/com/shaft/properties/internal/PropertiesHelper.java

- new flag added to control clear before typing 
key **clearBeforeTypingMode**
possible values : 
native ( to clear using native selenium clear ) 
backspace ( to delete letter by letter ) 
off ( no clear before typing ) 
- deprecating old flags 
attemptClearBeforeTyping , attemptClearBeforeTypingUsingBackspace

add clearBeforeTypingMode flag and deprecating old flags 

---

src/main/java/com/shaft/gui/element/internal/Actions.java
src/main/java/com/shaft/properties/internal/PropertiesHelper.java
src/test/java/testPackage/mockedTests/MultipleTypeCyclesTest.java

- new type was checking old flags only at the start of the test 
now checking also done during runtime till old flags are permanent removed 
- fixing multitype broken test

new Type compatibility with old clear before typing flags during runtime  

---

README.md
src/main/java/com/shaft/driver/internal/DriverFactory/LambdaTestHelper.java
src/main/java/com/shaft/properties/internal/LambdaTest.java

With this change, Shaft users executing Real-Device tests on LambdaTest will be able to select devices as per the specified geoLocation capability.
Verification was done by checking the Input Config (with capabilities passed via SHAFT) on the LambdaTest dashboard.

Geolocation caps for Real Device on LambdaTest

---

src/main/java/com/shaft/properties/internal/Allure.java
src/main/java/com/shaft/tools/io/internal/AllureManager.java

-allure.accumulateHistory=true
will now behave as expected, saving execution history and showing relevant trends to help identify flaky tests.
-allure.accumulateReports=true
will now be more relevant, as the report will hold details of the current test run only; previous run details will no longer show in the retries tab.

fix allure history and trends generation

---

src/main/java/com/shaft/driver/internal/DriverFactory/OptionsManager.java

this commit solves an issue when creating a Local Driver in Incognito Mode.

Solving BiDi Issue with Incognito Mode

---

src/main/java/com/shaft/listeners/TestNGListener.java
src/main/java/com/shaft/properties/internal/PropertiesHelper.java

- support early system properties setup needed for reporting and other key integrations via `PropertiesHelper.setKeySystemProperties();`
- reorganizing some actions inside the properties helper to ensure they are called in the right location.

reorganize engineSetup

---

src/main/java/com/shaft/api/RequestBuilder.java
src/test/java/testPackage/legacy/BasicAPITests.java

This PR refactors the API Request Builder to use `Map<String, Object>` for improved usability and readability.
- Added overloaded `setParameters(Map<String, Object>)`
- Deprecated old `List<List<Object>>` method for backward compatibility
- Updated tests and documentation
Closes #1912
- Verified functionality using unit tests.
- Ensured backward compatibility with existing implementations.
- This improves readability and maintainability while allowing a smooth transition.

Refactor API Request Parameters to Use Map<String, Object> for Improved Usability

---

src/main/java/com/shaft/api/RequestBuilder.java
src/test/java/testPackage/legacy/BasicAPITests.java

This PR adds "addHeaders" and "addCookies" methods to the API
Linked Issue
#1925 
You can try it out by doing this:
```
Map<String, String> headers = Map.of("Content-Type", "application/json", "Authorization", "Bearer token");
Map<String, String> cookies = Map.of("cookie_key", "cookie_value", "cookie_Key2", "cookie_value2");
restActions
.buildNewRequest(APIEndPoint, requestType)
.setHeaders(headers)
.setCookies(cookies)
.perform();
```

Add Headers and Add Cookies Features

---

.github/workflows/codeql-analysis.yml
.github/workflows/dependency_review.yml
.github/workflows/e2eTests.yml

with changing markdown files I do not need to run any code related pipeline workflows, so we disabled this.

chore: enhance pipeline by making tests run for needed changes

---

pom.xml
src/main/java/com/shaft/gui/element/internal/Actions.java
src/main/java/com/shaft/gui/internal/image/AnimatedGifManager.java
src/main/java/com/shaft/gui/internal/video/RecordManager.java
src/main/java/com/shaft/listeners/JunitListener.java
src/main/java/com/shaft/listeners/internal/JunitListenerHelper.java
src/main/java/com/shaft/tools/io/internal/ReportManagerHelper.java
src/main/resources/properties/default/junit-platform.properties

Issue fixed, and support for video recording should now work as expected for junit5 using the property
```properties
videoParams_recordVideo=true
```
same for the animated gif (which is extremely slow and highly not recommended unless you really have to)
```properties
createAnimatedGif=true
```

1986 bug video recording not working as expected in junit
